scripts/runner.py, scripts/service/gl/create_magazine.py
(cherry picked from commit f0d1888)
=> repair MagazineBot

scripts/runner.py, scripts/service/gl/create_magazine.py, tools/bot_scheduler.py, tools/bots_scheduler_test.py
- cast to integer
- try to optimize the update checker
=> bugfix for str in quality of proofread page

scripts/service/ws_re/register/authors.json
=> 190330_091015_updating_registers

scripts/service/ws_re/data_types.py, scripts/service/ws_re/scanner_tasks.py, scripts/service/ws_re/test_data_types.py, scripts/service/ws_re/test_scanner_tasks.py
- fetch lemma from RePage without prefix
- handle error if no lemma found in register to update
=> fix bug with the lemma Prefix

scripts/service/ws_re/register/III A_1.json, scripts/service/ws_re/register/III_1.json, scripts/service/ws_re/register/III_2.json, scripts/service/ws_re/register/II_1.json, scripts/service/ws_re/register/II_2.json, scripts/service/ws_re/register/IV_1.json, scripts/service/ws_re/register/IX_2.json, scripts/service/ws_re/register/I_1.json, scripts/service/ws_re/register/I_2.json, scripts/service/ws_re/register/VIII_1.json, scripts/service/ws_re/register/VII_1.json, scripts/service/ws_re/register/VI_1.json, scripts/service/ws_re/register/VI_2.json, scripts/service/ws_re/register/V_1.json, scripts/service/ws_re/register/XIII_2.json
=> 190418_205629_updating_registers

scripts/service/ws_re/register/III_1.json, scripts/service/ws_re/register/III_2.json, scripts/service/ws_re/register/IV_1.json, scripts/service/ws_re/register/S III.json, scripts/service/ws_re/register/VII A_2.json, scripts/service/ws_re/register/VII_2.json, scripts/service/ws_re/register/V_1.json, scripts/service/ws_re/register/XXI_2.json
=> 190512_155710_updating_registers

scripts/service/ws_re/scanner/__init__.py, scripts/service/ws_re/scanner/tasks/register_scanner.py, scripts/service/ws_re/scanner/tasks/test_register_scanner.py
- correct path
- add runtime for scanner
- suppress excessive logging
=> bugfix for wrong path to the register data

Makefile, scripts/service/ws_re/register/alphabetic.py, scripts/service/ws_re/register/lemma.py, scripts/service/ws_re/register/test_alphabetic.py, scripts/service/ws_re/register/test_lemma.py, scripts/service/ws_re/register/test_volume.py, scripts/service/ws_re/register/volume.py
- normal ... strong
- if redirect italic and the target strong
=> improve link formatting for the title

scripts/service/ws_re/register/data/II A_1.json, scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/V A_1.json, scripts/service/ws_re/register/data/VIII_1.json, scripts/service/ws_re/register/data/VII_1.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XI_1.json, scripts/service/ws_re/register/data/XVII_2.json, scripts/service/ws_re/register/data/XVI_2.json
=> 190624_111303_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/R.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XVIII_1.json, scripts/service/ws_re/register/data/XVIII_4.json, scripts/service/ws_re/register/data/XVI_1.json, scripts/service/ws_re/register/data/XXIII_1.json, scripts/service/ws_re/register/data/X_2.json
=> 190627_035814_updating_registers

scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S II.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/VIII_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json
=> 190628_011207_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/R.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VIII A_2.json, scripts/service/ws_re/register/data/VIII_1.json, scripts/service/ws_re/register/data/VIII_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XI_1.json, scripts/service/ws_re/register/data/XI_2.json, scripts/service/ws_re/register/data/XVIII_1.json
=> 190629_021222_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VIII_2.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XI_2.json
=> 190630_021247_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/R.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XIII_2.json, scripts/service/ws_re/register/data/XI_1.json, scripts/service/ws_re/register/data/XV_1.json, scripts/service/ws_re/register/data/XX_2.json
=> 190701_020623_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XVIII_3.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json, scripts/service/ws_re/register/data/XX_2.json
=> 190702_020605_updating_registers

scripts/service/ws_re/scanner/tasks/register_scanner.py
=> Revert "hotfix for failing re scanner"

scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/scanner/__init__.py
=> 190714_203443_updating_registers

scripts/service/ws_re/register/data/II A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/R.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XIV_1.json, scripts/service/ws_re/register/data/XI_1.json, scripts/service/ws_re/register/data/XVII_2.json
=> 190715_021156_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/R.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XVII_2.json
=> 190716_021328_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XIX_2.json, scripts/service/ws_re/register/data/XI_2.json
=> 190721_021347_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV A_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIII_2.json, scripts/service/ws_re/register/data/XII_2.json
=> 190722_021153_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/V A_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIV_2.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json
=> 190723_021208_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV A_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/VII A_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XV_1.json
=> 190724_021226_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/XI_1.json
=> 190725_021522_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/XVII_2.json
=> 190727_021320_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV A_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XXIII_1.json
=> 190729_021402_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S X.json
=> 190805_021300_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIV_1.json
=> 190806_020621_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S II.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XIII_2.json
=> 190809_021307_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json
=> 190810_021403_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XII_2.json
=> 190812_021344_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json
=> 190813_021259_updating_registers

scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/XVI_2.json
=> 190816_021522_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VII.json
=> 190817_021314_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIII.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json
=> 190818_021303_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/XI_2.json, scripts/service/ws_re/register/data/XXII_2.json
=> 190819_021304_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XIII_2.json, scripts/service/ws_re/register/data/XXII_2.json
=> 190820_021341_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json
=> 190821_021327_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/XIII_1.json
=> 190822_020559_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json
=> 190823_020543_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json
=> 190825_020541_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VII.json
=> 190826_020546_updating_registers

scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XIV.json
=> 190827_020542_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VII.json
=> 190828_020709_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/II A_1.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json, scripts/service/ws_re/register/data/XXII_2.json
=> 190829_020535_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json
=> 190830_020549_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/XIII_1.json
=> 190831_020531_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VIII_2.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XI_1.json, scripts/service/ws_re/register/data/XV_1.json
=> 190904_023708_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XIX_1.json
=> 190905_020341_updating_registers

scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/V A_2.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/XXII_1.json
=> 190909_020344_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VIII A_1.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/XIX_1.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_1.json, scripts/service/ws_re/register/data/XV_2.json
=> 190910_020348_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XIV_1.json, scripts/service/ws_re/register/data/XI_2.json
=> 190911_020339_updating_registers

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/VIII A_1.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XIV_1.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json
=> 190912_020338_updating_registers

scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XIII_1.json
=> 190913_020350_updating_registers

.circleci/config.yml, Makefile, tools/bot_scheduler.py, tools/bots.py
- correct declaration of List of classes
=> repair some type hint bubus

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json
=> 190916_020349_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/XIII_1.json
=> 190917_020400_updating_registers

scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XV_1.json
=> 190919_001854_updating_registers

scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S XII.json
=> 190927_020353_updating_registers

scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/VIII_2.json, scripts/service/ws_re/register/data/XI_2.json
=> 190928_020334_updating_registers

scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XIII_1.json
=> 190929_020321_updating_registers

scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VI.json
=> 190930_020336_updating_registers

scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XIII_1.json
=> 191001_023709_updating_registers

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIII_1.json
=> 191004_050357_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/V_1.json
=> 191007_050344_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S XII.json
=> 191009_050326_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIII_1.json
=> 191008_050337_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIII_1.json
=> 191010_050341_updating_registers

scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XI_2.json
=> 191011_050347_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json
=> 191012_050324_updating_registers

scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json
=> 191013_050514_updating_registers

scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/XIII_1.json
=> 191014_050354_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XIII_1.json
=> 191015_050334_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json
=> 191016_050350_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json
=> 191017_050352_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json
=> 191018_050349_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S XII.json
=> 191019_050406_updating_registers

scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/V_2.json
=> 191020_050349_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S XII.json
=> 191022_050554_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XVI_2.json
=> 191023_050323_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S XII.json
=> 191024_050401_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/XVI_2.json, scripts/service/ws_re/register/data/XV_2.json
=> 191111_061413_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/V A_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XVI_1.json
=> 191202_050918_updating_registers

scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json
=> 191209_052336_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/X_2.json
=> 191213_052310_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX A_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IV.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/VIII_1.json, scripts/service/ws_re/register/data/VIII_2.json, scripts/service/ws_re/register/data/VII_1.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XII_2.json, scripts/service/ws_re/register/data/XI_1.json, scripts/service/ws_re/register/data/XVIII_1.json, scripts/service/ws_re/register/data/XV_1.json
=> 191215_053102_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/V A_2.json, scripts/service/ws_re/register/data/VII_1.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIV_2.json
=> 191216_054230_updating_registers

scripts/service/ws_re/register/data/V A_2.json, scripts/service/ws_re/register/data/VII_1.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/VI_2.json
=> 191218_052312_updating_registers

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/VII_1.json, scripts/service/ws_re/register/data/V_1.json
=> 191223_052729_updating_registers

scripts/service/ws_re/register/data/II A_1.json, scripts/service/ws_re/register/data/III A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S IX.json, scripts/service/ws_re/register/data/S V.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VIII_1.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XIII_2.json, scripts/service/ws_re/register/data/XII_1.json, scripts/service/ws_re/register/data/XII_2.json, scripts/service/ws_re/register/data/XXII_1.json
=> 200101_063937_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json
=> 200105_061209_updating_registers

scripts/service/ws_re/register/data/III A_1.json
=> 200105_113425_updating_registers

scripts/service/ws_re/register/data/III A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/V_1.json
=> 200106_052707_updating_registers

scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S VII.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/XIII_1.json, scripts/service/ws_re/register/data/XIX_1.json
=> 200107_052737_updating_registers

scripts/service/ws_re/register/data/I_1.json
=> 200108_005755_updating_registers

scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json
=> 200119_005307_updating_registers

scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/V_1.json
=> 200122_021458_updating_registers

scripts/service/ws_re/register/data/III A_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/V_1.json
=> 200123_013645_updating_registers

scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/V_1.json
=> 200125_012808_updating_registers

scripts/service/ws_re/register/data/V A_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json
=> 200126_012623_updating_registers

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/V_1.json
=> 200127_012449_updating_registers

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S X.json, scripts/service/ws_re/register/data/V A_1.json, scripts/service/ws_re/register/data/VII_2.json, scripts/service/ws_re/register/data/V_1.json
=> 200128_013522_updating_registers

scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/S VIII.json, scripts/service/ws_re/register/data/V_1.json
=> 200129_012722_updating_registers

scripts/service/ws_re/register/data/III A_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIV_1.json
=> 200130_021117_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/VI_2.json
=> 200131_012817_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/VIII A_2.json
=> 200201_020922_updating_registers

scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/VII A_1.json
=> 200202_015528_updating_registers

scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/V_1.json
=> 200203_012110_updating_registers

scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIX_1.json, scripts/service/ws_re/register/data/X_2.json
=> 200204_021822_updating_registers

scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/VII A_2.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/XIII_2.json, scripts/service/ws_re/register/data/XII_2.json
=> 200205_012546_updating_registers

scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/V_1.json
=> 200206_014809_updating_registers

scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/authors.json
=> 200209_013140_updating_registers

scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/V_1.json
=> 200210_014534_updating_registers

scripts/service/ws_re/register/data/I A_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/VIII_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/X_1.json
=> 200211_012953_updating_registers

scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/V_1.json
=> 200212_012929_updating_registers

scripts/service/ws_re/register/data/II_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/V_1.json
=> 200213_012814_updating_registers

scripts/service/ws_re/register/data/I A_1.json, scripts/service/ws_re/register/data/III_1.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IV_1.json, scripts/service/ws_re/register/data/IV_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S I.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/S VI.json, scripts/service/ws_re/register/data/S XII.json, scripts/service/ws_re/register/data/S XIV.json, scripts/service/ws_re/register/data/S XV.json, scripts/service/ws_re/register/data/V A_1.json, scripts/service/ws_re/register/data/VI_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XIX_1.json, scripts/service/ws_re/register/data/XX_2.json, scripts/service/ws_re/register/data/X_1.json
=> 200214_082627_updating_registers

scripts/service/ws_re/register/data/III A_1.json, scripts/service/ws_re/register/data/II_2.json, scripts/service/ws_re/register/data/I_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/V A_2.json, scripts/service/ws_re/register/data/VII_1.json, scripts/service/ws_re/register/data/VI_1.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json, scripts/service/ws_re/register/data/XV_2.json, scripts/service/ws_re/register/data/X_1.json
=> 200215_091438_updating_registers

scripts/service/ws_re/register/data/II A_2.json, scripts/service/ws_re/register/data/III_2.json, scripts/service/ws_re/register/data/IX_1.json, scripts/service/ws_re/register/data/I_2.json, scripts/service/ws_re/register/data/S III.json, scripts/service/ws_re/register/data/VIII_2.json, scripts/service/ws_re/register/data/V_1.json, scripts/service/ws_re/register/data/V_2.json
=> 200217_064025_updating_registers

scripts/service/ws_re/scanner/tasks/wikidata/__init__.py, scripts/service/ws_re/scanner/tasks/wikidata/copyright_status_claims.py
=> add further public domain claim

service/ws_re/scanner/base.py, service/ws_re/scanner/tasks/wikidata/task.py
=> [end test run] no restriction for items per night

service/protect.py, service/ws_re/scanner/base.py
run the protect bot for longer
=> finish Scanner around 4:00, to prevend push issues

service/ws_re/scanner/tasks/register_scanner.py, service/ws_re/scanner/tasks/test_register_scanner.py, service/ws_re/scanner/tasks/wikidata/claims/claim_factory.py, service/ws_re/template/re_page.py, service/ws_re/template/test_re_page.py
=> refactor splitted article list to not contain pure strings ... 

requirements-dev.txt, requirements.txt, service/protect.py, service/test_protect.py
This PR changes the behavior of the Protect bot. Lemmas which changed back from Fertig shouldn't be protected anymore.
=> handle lemmas which changed back from Fertig

requirements-dev.txt, requirements.txt, tools/petscan.py, tools/test_petscan.py
workaround for: https://github.com/magnusmanske/petscan_rs/issues/148
=> Retry for Petscan calls
